name: inventory-exporter # you probably want to 'snapcraft register <name>'
base: core20
version: '0.1'
summary: Exporter for apt packages and snaps in json via web
description: |
  This snap runs a simple python http server that serves apt packages and snaps
  in json format.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [amd64]

parts:
  exporter:
    plugin: python
    source: .

apps:
  inventory-exporter:
    command: bin/exporter
    daemon: simple
