name: software-inventory-exporter
base: core22
adopt-info: software-inventory-exporter
summary: Exporter for apt packages and snaps in json via web
license: GPL-3.0
description: |
  This snap runs a simple python http server that serves apt packages and snaps
  in json format.
grade: stable
confinement: strict
environment:
  PYTHONPATH: $SNAP/lib/python3.10/site-packages:$PYTHONPATH

architectures:
  - build-on: [amd64]

plugs:
  snap-apt-dpkg-db:
    interface: system-files
    read:
      - /var/lib/snapd/hostfs/var/lib/dpkg
      - /var/lib/snapd/hostfs/var/cache/apt
      - /etc/apt
      - /etc/dpkg
      - /var/lib/snapd/state.json
      - /snap

layout:
  /usr/share/dpkg:
    bind: $SNAP/usr/share/dpkg
  /usr/bin/dpkg:
    bind-file: $SNAP/usr/bin/dpkg
  /etc/dpkg/dpkg.cfg:
    bind-file: $SNAP/etc/dpkg/dpkg.cfg

apps:
  software-inventory-exporter:
    command: bin/software-inventory-exporter $SNAP_DATA/config.yaml
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network
      - network-bind
      - snap-apt-dpkg-db

parts:
  software-inventory-exporter:
    plugin: python
    source: .
    python-requirements: [./requirements.txt]
    stage-packages:
      - dpkg
      - git
    python-packages:
      - .
    override-build: |
        snapcraftctl build
        echo "Version: $(python3 setup.py --version)"
        craftctl set version="$(python3 setup.py --version)"
